theme: jekyll-theme-cayman
title: Protopipe
description: Speed up your machine learning workflows
baseurl: /protopipe_web
permalink: /404.html

company:
  name: A Company With No Name
  email: nitzing`.and.more`{:.antispam}@gmail.com
  url: http://twitter.com

github:
  is_project_page: false

exclude: ["_*"]
